#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V VI VII VIII IX X

# Window Gaps
bspc config border_width         1
bspc config window_gap           1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rounded corners
bspc config window_corner_radius 10

# Hover to focus enable
bspc config focus_follows_pointer true


# Autostart Application
sxhkd &
nitrogen --restore &
picom --config ~/.config/picom/picom.conf &

# 1. Reserve space at the top (38px matches your bar height)
bspc config top_padding 38

# 2. Kill any old bar instances before starting a new one
killall -q lemonbar bar.sh

# 3. Launch your script
~/.config/lemonbar/bar.sh &

# For japanese Language
fcitx5 -d &
